### PR TITLE
Added .p-fileupload-highlight class

### PR DESCRIPTION
**Pull request by SoyDiego**
Added file .p-fileupload-highlight class to fix https://github.com/primefaces/primereact/pull/4646

I have follow the same idea like:
PrimeNG: https://github.com/primefaces/primeng-sass-theme/pull/24
PrimeVue: https://github.com/primefaces/primevue-sass-theme/pull/14

## PROBLEM

when I'm trying to drag over my file in the component (nothing was happening)

problem fileupload primereact

## SOLUTION
fixed fileupload primereact

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by SoyDiego** [comment]
Hi @habubey are you review or checking the PR's?
Thanks

**Comment by habubey** [comment]
> Hi @habubey are you review or checking the PR's? Thanks

Thanks for the PR, we will check and get back to you soon @SoyDiego  😉

**Comment by SoyDiego** [comment]
> > Hi @habubey are you review or checking the PR's? Thanks
> 
> Thanks for the PR, we will check and get back to you soon @SoyDiego wink

Thanks for your fast reply, it's not pressure, only I'm trying to help and contributing in the primetek projects (more in primeng at the moment)  and for that sometimes it's a little bit difficult without replies of the core team.
Thanks again!

**Comment by SoyDiego** [comment]
> I looked at your PR and it looks good. I'll talk to my teammates in NG and Vue and get back to you. As you know, since this change includes NG, Vue, and React, we will make a joint decision to harmonize the libraries. @SoyDiego

Thanks for the review and your fast reply. I did the same PR in all the projects (NG, React, Vue). Here you have the links to share with your team:
PrimeNG: https://github.com/primefaces/primeng-sass-theme/pull/24
PrimeVue: https://github.com/primefaces/primevue-sass-theme/pull/14

Thanks again

**Comment by ulasturann** [comment]
Hi @SoyDiego,

Thank you for the PR.

I noticed an issue regarding the border styles. The $panelContentBorder is 1px solid, so the 2px border from .p-fileupload-highlight causes a shift in the container. Adjusting just the border's color and style should fix it

.p-fileupload-content {
    background: $panelContentBg;
    padding: $fileUploadContentPadding;
    border: $panelContentBorder;
    color: $panelContentTextColor;
    border-bottom-right-radius: $borderRadius;
    border-bottom-left-radius: $borderRadius;

    &.p-fileupload-highlight {
        border-color: $primaryColor;
        border-style: dashed;
        background-color: $highlightBg;
    }
}

**Comment by SoyDiego** [comment]
> Hi @SoyDiego,
> 
> Thank you for the PR.
> 
> I noticed an issue regarding the border styles. The $panelContentBorder is 1px solid, so the 2px border from .p-fileupload-highlight causes a shift in the container. Adjusting just the border's color and style should fix it
> 
> .p-fileupload-content { background: $panelContentBg; padding: $fileUploadContentPadding; border: $panelContentBorder; color: $panelContentTextColor; border-bottom-right-radius: $borderRadius; border-bottom-left-radius: $borderRadius;
> 
> ```
> &.p-fileupload-highlight {
>     border-color: $primaryColor;
>     border-style: dashed;
>     background-color: $highlightBg;
> }
> ```
> 
> }

Thanks @ulasturann. I did a new commit removing the border

**Comment by ulasturann** [comment]
@SoyDiego , Actually in some themes, variables like $primaryColor used in the current change don't exist, so it's an issue that needs to be examined for all cases. We'll review this within our team and get back. Thanks again

**Comment by SoyDiego** [comment]
> @SoyDiego , Actually in some themes, variables like $primaryColor used in the current change don't exist, so it's an issue that needs to be examined for all cases. We'll review this within our team and get back. Thanks again

Hi @ulasturann @ulasturann,
Any news about this or how the problem will be resolved in themes that do not have `$primaryColor`?

Thanks =)

**Comment by SoyDiego** [comment]
Hi @ulasturann @habubey,
I'm writting again here asking if you have any news about this or how the problem will be resolved in themes that do not have $primaryColor?

Thanks =)

**Comment by melloware** [comment]
cc @gucal cc @nitrogenous

**Comment by gucal** [comment]
Thank you for your contribution.

**Comment by SoyDiego** [comment]
> Thank you for your contribution.

Thanks for merge. Will not bring conflicts with the things that commented @ulasturann before?

```
@SoyDiego , Actually in some themes, variables like $primaryColor 
used in the current change don't exist, so it's an issue that needs to be 
examined for all cases. We'll review this within our team and get back. Thanks again
```

**Comment by gucal** [comment]
Hi,
I will write to you again as soon as possible. For now, it may remain like this.

**Comment by SoyDiego** [comment]
> Hi,
> I will write to you again as soon as possible. For now, it may remain like this.

Sure, no problem, thanks @gucal

**Pull request merged**
